- name: setup syslog output to graylog
  lineinfile: dest=/etc/rsyslog.conf line="$template GRAYLOGRFC5424,\"<%PRI%>%PROTOCOL-VERSION% %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% %MSGID% %STRUCTURED-DATA% %msg%\"\n*.* @@infra-logs.vivareal.com:514;GRAYLOGRFC5424" state=present
